openai:
  OPENAI_API_KEY: ''
  OPENAI_API_BASE: ''
  OPENAI_ORGANIZATION: ''

azure:
  AZURE_OPENAI_API_KEY: ''
  AZURE_OPENAI_ENDPOINT: ''
  OPENAI_API_VERSION: '2024-06-01'

google:
  GOOGLE_API_KEY: ''